version: '3.8'

services:
  projectnetworks-site:
    build: .
    container_name: projectnetworks-site
    restart: unless-stopped
    ports:
      - "8083:80"
    networks:
      - web

networks:
  web:
    driver: bridge
